### ISSUE TITLE
Windows Defender报毒

### ISSUE THREAD

**Issue by LiGhauNgyan** [DawnFz/GenShin-LauncherDIY#1]
国服切换到国际服再切换回来时启动器（v1.0.4）被Windows Defender删除，报毒信息

> 已检测: Trojan:Script/Wacatac.B!ml

> 状态: 已隔离

>  详细信息: 这个程序很危险，而且执行来自攻击者的命令。

> 受影响的项目: e:\genshin launcher\genshin.launcher.plus.1.0.4.exe

**Comment by DawnFz** [comment]
这个我没办法  Orz  ，毕竟切换国际服要修改文件，建议试试在Windows Defender里把启动器排除掉
