### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by qw1324** [DawnFz/GenShin-LauncherDIY#10]
启动器在线更新失败
版本: 1.1.6.0
ini文件内容不正确或者其他因素

![image](https://user-images.githubusercontent.com/49418651/145689294-d82d8e51-d1f7-4b45-ba47-f2ecd18a18f2.png)

**Comment by DawnFz** [comment]
应该是偶发性问题，我去解决一下

**Comment by qw1324** [comment]
偶发性问题 我每次使用在线更新 100%出现

ねねだん ***@***.***> 于 2021年12月12日周日 上午3:37写道：

**Comment by DawnFz** [comment]
已经修复了，前天的1.1.7和昨天的1.1.8均不会出现，不过还是先建议删除Update.exe让启动器重新生成

**Comment by qw1324** [comment]
请问一下 这个路径在哪里

ねねだん ***@***.***> 于 2021年12月12日周日 上午11:27写道：

**Comment by DawnFz** [comment]
就在启动器（原神启动器plus）的根目录

**Comment by qw1324** [comment]
可以说一下具体吗 我之前有找过一次 没找着

ねねだん ***@***.***> 于 2021年12月12日周日 上午11:30写道：

**Comment by DawnFz** [comment]
就是你放原神启动器plus的那个文件夹里，不是有unlockfps.exe和update.exe吗，把后者删了就行了，启动器会生成新的

**Comment by qw1324** [comment]
草 原来要创文件夹才有的 谢谢帮忙啦

ねねだん ***@***.***> 于 2021年12月12日周日 上午11:36写道：
