### ISSUE TITLE
可否增加不能同时开多个启动器的限制？

### ISSUE THREAD

**Issue by CHxCOOH** [DawnFz/GenShin-LauncherDIY#11]
现在版本是没有这个feature的，本来在增加最小化到托盘这个功能之前，逻辑上也不会有太大问题。但是现在就很容易出现游戏开了之后最小化启动器，然后游戏关了就被忘记了，再开启动器开多个的情况，我就有过同时开三四个的经历Orz
希望可以优化一下w

**Comment by DawnFz** [comment]
已经优化了
    	获取 Outlook for iOS
    
  

 发件人: ***@***.*** ***@***.***> 代表 NaHCOx ***@***.***>发送时间: 星期二, 十二月 14, 2021 01:55收件人: DawnFz/GenShin-LauncherDIY抄送: Subscribed主题: [DawnFz/GenShin-LauncherDIY] 可否增加不能同时开多个启动器的限制？ (Issue #11) 
现在版本是没有这个feature的，本来在增加最小化到托盘这个功能之前，逻辑上也不会有太大问题。但是现在就很容易出现游戏开了之后最小化启动器，然后游戏关了就被忘记了，再开启动器开多个的情况，我就有过同时开三四个的经历Orz
希望可以优化一下w
