### ISSUE TITLE
用了这个，会把我状态栏自动隐藏掉

### ISSUE THREAD

**Issue by skylovebeauty** [DawnFz/GenShin-LauncherDIY#14]
如题，这个工具非常好用，包括解锁帧率的。但是用了之后（一点 开始游戏，到解除帧率画面），就会把我windows操作系统桌面最下面的状态栏给隐藏掉。。。是不是有什么我使用不当的地方？

**Comment by DawnFz** [comment]
已经修复了
    	获取 Outlook for iOS
    
  

 发件人: ***@***.*** ***@***.***> 代表 skylovebeauty ***@***.***>发送时间: 星期一, 十二月 20, 2021 22:40收件人: DawnFz/GenShin-LauncherDIY抄送: Subscribed主题: [DawnFz/GenShin-LauncherDIY] 用了这个，会把我状态栏自动隐藏掉 (Issue #14) 

如题，这个工具非常好用，包括解锁帧率的。但是用了之后（一点 开始游戏，到解除帧率画面），就会把我windows操作系统桌面最下面的状态栏给隐藏掉。。。是不是有什么我使用不当的地方？
