### ISSUE TITLE
转换失败，文件却被删掉了

### ISSUE THREAD

**Issue by onefork** [DawnFz/GenShin-LauncherDIY#15]
原本安装的是国际服，第一次运行本启动器，复原功能可用（实际应禁用？）。使用复原功能后，游戏无法运行，但游戏exe文件好像已经被删掉了，也不能回退。

百度网盘下载GlobalFile.pkg恢复了游戏文件。

请增加回滚/备份机制，另外能否参考补丁安装的常规做法，一次转换的各个文件操作视为一个原子操作处理。如果因为这种小小的问题，需要重新下载游戏，就不够周全了。

谢谢，辛苦！

**Comment by DawnFz** [comment]
因为启动器不支持原国际转国内双端，只支持原国内的和国际互转，最近比较忙，等过了元旦之后大更新一次



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 凌晨1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [DawnFz/GenShin-LauncherDIY] 转换失败，文件却被删掉了 (Issue #15)





 
原本安装的是国际服，本启动器恢复功能可用（实际应禁用？），使用恢复功能后，游戏无法运行，但exe文件好像已经被删掉了，也不能回退。
 
请增加回滚/备份机制，谢谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
