### ISSUE TITLE
1.2.1跳转浏览器闪退

### ISSUE THREAD

**Issue by sertwen** [DawnFz/GenShin-LauncherDIY#16]
设置-国际服转换-转换-确定转换-确定
启动器无响应，之后闪退
密码已成功复制到剪贴板，但是不知道下载链接

**Comment by Silence-dream** [comment]
> 设置-国际服转换-转换-确定转换-确定 启动器无响应，之后闪退 密码已成功复制到剪贴板，但是不知道下载链接

https://pan.baidu.com/s/1-5zQoVfE7ImdXrn8OInKqg
