### ISSUE TITLE
是否有可能把启动器也一并转换了

### ISSUE THREAD

**Issue by TheCGDF** [DawnFz/GenShin-LauncherDIY#18]
~~既然要追求刺激，那就贯彻到底？~~
转换成国际服的启动器？

**Comment by DawnFz** [comment]
这个没什么必要啊（（
    	获取 Outlook for iOS
    
  

 发件人: ***@***.*** ***@***.***> 代表 CGDF ***@***.***>发送时间: 星期日, 一月 9, 2022 18:25收件人: DawnFz/GenShin-LauncherDIY抄送: Subscribed主题: [DawnFz/GenShin-LauncherDIY] 是否有可能把启动器也一并转换了 (Issue #18) 

既然要追求刺激，那就贯彻到底？

转换成国际服的启动器？
