### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by daofeng2015** [DawnFz/GenShin-LauncherDIY#2]
1:窗口分辨率应该增加几个常用的选项
2:游戏文件路径应该可以选择文件夹的功能(注册表应该也有),最后配个选择那个文件夹的图,启动器的文件夹名称和游戏路径一样容易弄混淆
3:那个资源包你可以自己搞个阿里云盘存,然后搞个前端获取下载地址就行了,百度限速太恶心了

**Comment by DawnFz** [comment]
收到建议，谢谢你的建议，我会在下个版本加进去，刚开始我试过阿里云盘，我的盘说不支持这种格式文件分享，zip也不行才用了度盘，我看看有什么办法能在阿里云上分享

**Comment by daofeng2015** [comment]
> 收到建议，谢谢你的建议，我会在下个版本加进去，刚开始我试过阿里云盘，我的盘说不支持这种格式文件分享，zip也不行才用了度盘，我看看有什么办法能在阿里云上分享
> […](#)
> 在 2021年11月30日，13:17，蒋 ***@***.***> 写道： ﻿ 1:窗口分辨率应该增加几个常用的选项 2:游戏文件路径应该可以选择文件夹的功能(注册表应该也有),最后配个选择那个文件夹的图,启动器的文件夹名称和游戏路径一样容易弄混淆 3:那个资源包你可以自己搞个阿里云盘存,然后搞个前端获取下载地址就行了,百度限速太恶心了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

 我说的不是分享文件那种的,类似于 https://github.com/libsgh/PanIndex 这样的项目 可以通过api随意分享

**Comment by DawnFz** [comment]
这还得整一台服务器，毕竟如果启动器直接获取资源的话还得用到直链，要实现从网盘变直链的话确实要用到你给的那个项目里的方法或者累似的方法，而且不一定稳定，虽然这种定时获取网盘资源列表并且转换成直链的轻量应用用不上性能多好的服务器，但是我本来也没这方面的需求，没打算用爱发电到再去整一台服务器来弄，道理我都懂。要直链也可以直接把资源包扔到云对象存储里去还比开个服务器便宜，但是实际上完全没这个必要，度盘限速确实恶心，但是对于这一百来兆的小资源试用个加速基本上都能下载好，虽然但是，我还是会尽量去找找有没有方便而且不限速的网盘

**Comment by zhoupengjie** [comment]
系统在150%缩放系数的时候，点击取适合21：9选项，分辨率会被调到2213*948，实际分辨率为3440*1440
