### ISSUE TITLE
对国际服客户端转换国服的一些建议

### ISSUE THREAD

**Issue by zhouxuanyi-zxy** [DawnFz/GenShin-LauncherDIY#20]
转换后的备份文件建议放在除了根目录其他的一个单独文件夹（或者直接先删除，然后直接用GlobalFile.pkg还原），不然国服直接31-4302
![image](https://user-images.githubusercontent.com/69704410/150111004-d156d515-92b4-4868-b1b4-7903b7515964.png)
而转换回来的国际服却没有问题
因为我之前不小心从国际服转到了B服，然后又无法转回来，于是我直接手动替换+改名，最后是因为B服的SDK没删才导致国际服31-4302，所以我推测国际服转国服的问题也是出现在备份文件的地址
（以下是转换成国服的文件夹目录\Genshin Impact game\YuanShen_Data\Plugins\）
![image](https://user-images.githubusercontent.com/69704410/150111694-c6276416-5442-4f6b-9d6c-2f6054ced764.png)
（以下是转换回国际服的文件夹目录\Genshin Impact game\GenshinImpact_Data\Plugins\）
![image](https://user-images.githubusercontent.com/69704410/150112089-6ff83cfb-49a3-446e-8889-8cb39c6a1b80.png)
我说的就是那些*.bak文件，建议放在游戏根目录外，等还原再移回来
![image](https://user-images.githubusercontent.com/69704410/150112933-914ce595-9e6c-4a1e-b849-781ba17a1ecc.png)
（以上是转换回来的国际服，可正常运行）

**Comment by DawnFz** [comment]
已经修复

**Comment by zhouxuanyi-zxy** [comment]
但是仍然如此
![image](https://user-images.githubusercontent.com/69704410/151366545-860f3da8-1319-4741-8d16-cc198fdf2d0f.png)
