### ISSUE TITLE
安装.NET6正在运行时后仍然弹出“未安装.NET”窗口

### ISSUE THREAD

**Issue by mcwuguodadi** [DawnFz/GenShin-LauncherDIY#22]
![QQ图片20220127160556](https://user-images.githubusercontent.com/82522552/151316939-c5dba905-ef62-4bdc-8ad1-6860a0b420c9.png)
如图，重启后仍然报错

**Comment by Lightczx** [comment]
.NET `Desktop` Runtime x64

**Comment by Lightczx** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.1-windows-x64-installer

**Comment by mcwuguodadi** [comment]
好了，没想到是Desktop Runtime不是Runtime x64....
