### ISSUE TITLE
关于分辨率设置的想法

### ISSUE THREAD

**Issue by dmnbme** [DawnFz/GenShin-LauncherDIY#25]
大佬好哇( *｀ω´)
现在Launcher里的分辨率设置是固定的，这对拥有多块屏幕的用户来说并不友好(つд⊂)
比如经常要在外接屏和笔记本屏之间切换的我( ;´д`)
所以可否添加一个【使用默认全屏分辨率】的选项呢(〃∀〃) #

**Comment by DawnFz** [comment]
好的，已经加上了，但是最近没时间更新，等有时间了再发布新版本
