### ISSUE TITLE
Translate this

### ISSUE THREAD

**Issue by prpjzz** [DawnFz/GenShin-LauncherDIY#28]
Hi, I would like to translate your tool into English language. Can I help you?

And I also hope your tool can be used in Global version.

Thanks.

**Comment by Lightczx** [comment]
it support Global exactly, just some little translations is needed

**Comment by DawnFz** [comment]
what country are you from,Can you understand Chinese? I am planning to improve this program into a multilingual version, It is expected to be online within a week,At that time, multiple languages will be implemented with language packs,The theory supports the language of any country, as long as someone makes the corresponding language package,But my English is not good, can you please help me make the English language pack?-----------------This text is translated by Google

**Comment by DawnFz** [comment]
已经发布支持多语言的版本，等待各路大神制作相应国家的语言包
