### ISSUE TITLE
发布途径

### ISSUE THREAD

**Issue by Ipmlosion** [DawnFz/GenShin-LauncherDIY#3]
希望直接在GitHub发包，国内可以用Gitee做镜像站
不要度盘，不要度盘，不要度盘，度盘这玩意太司马了

**Comment by Fidelxyz** [comment]
@DawnFz 推荐一个免费网盘：https://own-cloud.cn/index.html

我自己用了两年多了，一直稳定

支持任意文件格式分享，下载速度也不错
