### ISSUE TITLE
最新1.2.9.0版本无法正常启动

### ISSUE THREAD

**Issue by Mei-Sakura** [DawnFz/GenShin-LauncherDIY#30]
系统为win11 dev 22543
1.2.8.0版本正常启动，更新后无法正常启动只有进程不显示界面
删除重新下载   重装.NET 6.0均无效

另外一台win11 dev 22557系统正常，初步认为应该是启动器最近更新版本问题

![image](https://user-images.githubusercontent.com/81066884/154976057-fb4e5f57-e32e-4d1a-aeca-a38e8e6ba5f7.png)

**Comment by wayne0036** [comment]
遇到了同样的问题

版本	Windows 10 企业版
版本号	21H2
安装日期	‎2020-‎07-‎01
操作系统内部版本	19044.1526
体验	Windows Feature Experience Pack 120.2212.3920.0

**Comment by shoucandanghehe** [comment]
Windows 11 专业版 22000.527
直接运行1.2.9无窗口
运行1.2.8后再运行1.2.9正常

**Comment by Lightczx** [comment]
DGP-Studio/Snap.Genshin#176
