### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by demaciapony** [DawnFz/GenShin-LauncherDIY#31]
之前一直可以打开的，更新到1.3.0.3后反而打不开了

**Comment by bsnawoke** [comment]
删了下1.2.9也打不开

**Comment by Phycanva** [comment]
更新到1.3.0.3后打不开（已安装.Net 6.0.2 x64环境），1.2.9正常

**Comment by DawnFz** [comment]
【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【armx64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】

**Comment by DawnFz** [comment]
【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【arm64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】！

**Comment by 1061875478** [comment]
如果已经安装runtime 6.0.2 x64后仍然无法运行，可以检查是否安装过.net sdk,我之前vs装的是6.0.1sdk，无论怎么安装runtime 6.0.2 x64都无效，更新sdk就好了，里面包含runtime

**Comment by 1061875478** [comment]
如果已经安装runtime 6.0.2 x64后仍然无法运行，可以检查是否安装过.net sdk,我之前vs装的是6.0.1sdk，无论怎么安装runtime 6.0.2 x64都无效，更新sdk就好了，里面包含runtime

**Comment by bsnawoke** [comment]
> 如果已经安装runtime 6.0.2 x64后仍然无法运行，可以检查是否安装过.net sdk,我之前vs装的是6.0.1sdk，无论怎么安装runtime 6.0.2 x64都无效，更新sdk就好了，里面包含runtime

确实，重新试了下，有6.0.1的SDK的情况下runtime的安装无效，SDK更新为6.0.2即可

**Comment by shiroringo** [comment]
> 【Windows桌面运行时 6.0.2 X64】请注意是【X64】的【6.0.2】的【桌面运行时】，不要下载【arm64】和【x86】版本的，不要下载【运行时】，看清楚是【Windows桌面运行时 6.0.2 X64】！

说的很对，我就下成了x86
