### ISSUE TITLE
关于启动器自启动速度的优化建议

### ISSUE THREAD

**Issue by Mark9804** [DawnFz/GenShin-LauncherDIY#32]
1. 能不能考虑把检查更新的步骤推迟到主界面绘制完成之后，或者做成异步
2. 能不能考虑把从网络获取开屏图片的步骤做成异步

我感觉这两步大大拖慢了启动速度，特别是当检查到有更新之后，从运行到弹出更新窗口要等一万年……

**Comment by DawnFz** [comment]
好的，收到
