### ISSUE TITLE
转换服务器功能不稳定

### ISSUE THREAD

**Issue by KFC0803** [DawnFz/GenShin-LauncherDIY#35]
国际服转国服，一共测试了四次。第一次打开杀软成功转换；第二次打开杀软生成.bak文件后启动器崩溃；第三次关闭杀软成功转换；第四次关闭杀软生成.bak文件后启动器崩溃。

**Comment by DawnFz** [comment]
杀软问题我就不管了，提示警告里写的明明白白，不稳定完全是操作问题
