### ISSUE TITLE
无法启动Launcher

### ISSUE THREAD

**Issue by NekoMua** [DawnFz/GenShin-LauncherDIY#36]
使用事件查看器查看报错
[-](https://github.com/DawnFz/GenShin-LauncherDIY/issues/new#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/DawnFz/GenShin-LauncherDIY/issues/new#) <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022[-](https://github.com/DawnFz/GenShin-LauncherDIY/issues/new#)03-05T13:21:20.3775929Z" /> 
  <EventRecordID>18411</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="16440" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>猫様のlaptop</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: GenShin-Launcher.exe CoreCLR Version: 6.0.222.6406 .NET Version: 6.0.2 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.VisualBasic.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040) File name: 'Microsoft.VisualBasic.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at GenShin_Launcher_Plus.SingletonApp.Main(String[] args)</Data> 
  </EventData>
  </Event>
和
[-](https://github.com/DawnFz/GenShin-LauncherDIY/issues/new#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/DawnFz/GenShin-LauncherDIY/issues/new#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022[-](https://github.com/DawnFz/GenShin-LauncherDIY/issues/new#)03-05T13:21:20.4395922Z" /> 
  <EventRecordID>18412</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="3224" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>猫様のlaptop</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>GenShin-Launcher.exe</Data> 
  <Data>1.3.1.0</Data> 
  <Data>61e1d8d9</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.22000.434</Data> 
  <Data>72a6f702</Data> 
  <Data>e0434352</Data> 
  <Data>000000000004478c</Data> 
  <Data>4038</Data> 
  <Data>01d83093e717e501</Data> 
  <Data>E:\Genshin Impact\GenShin-Launcher.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>4c10b9fe-e195-43a3-9c11-b0362b52c330</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by Lightczx** [comment]
#31
