### ISSUE TITLE
游戏本体目录名不为“Genshin Impact Game"时无法识别游戏存在

### ISSUE THREAD

**Issue by lensferno** [DawnFz/GenShin-LauncherDIY#6]
我的游戏本体是放在“D:\Games\Genshin Impact”中的，按照启动器的指示，填入"D:\Games"，依然提示”游戏文件不存在“，将目录”Genshin Impact“改为”Genshin Impact Game“能正常识别启动，希望能够解决该问题。 

查找代码发现是由于代码中写定了游戏文件在"Genshin Impact Game"这个文件夹中，
我的想法是读取官方启动器中的config来获得真正的游戏目录，或者直接填入游戏本体exe文件所在的目录，而不是”Genshin Impact Game“所在的位置（即填入“D:\Games\Genshin Impact”）
不过配置文件向下兼容的工作会比较麻烦...

**Comment by DawnFz** [comment]
收到反馈
