### ISSUE TITLE
自定义启动器图片

### ISSUE THREAD

**Issue by chenshoyuan** [DawnFz/GenShin-LauncherDIY#9]
希望能自定义启动器图片

**Comment by DawnFz** [comment]
可以的，把png格式的（1280×730或者同等比例）的图片改名bg.png放到config文件夹就可以了

**Comment by chenshoyuan** [comment]
问一下好像没有这个文件，网盘分享的只是exe程序改不了图片

**Comment by DawnFz** [comment]
默认是没这个文件的，有这个文件的话启动器就优先使用这个图片，没有的话就用的是启动器默认的
